### ISSUE TITLE
caso 4.2.0 not functional due to non-annotated attribute `public_ip_count = 0`

### ISSUE THREAD

**Issue by freznicek** [IFCA-Advanced-Computing/caso#131]
### Description

caso at latest version 4.2.0 is not usable at all as pydantic asserts non-annotated attribute `public_ip_count = 0`

### Steps to Reproduce

1. python3 -m pip install caso
2. caso-extract --help

### Expected behavior:

caso showing at least help message

### Actual behavior

Any caso 4.2.0 invocation fails

### Versions

```
[freznicek@lenovo-t14 caso 0]$ podman run -it --rm ubuntu:jammy
root@5ff66be7f372:/# apt update && apt -y install python3-minimal python3-pip
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
...
done.
root@5ff66be7f372:/# python3 -m pip install caso
Collecting caso
  Downloading caso-4.2.0-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.3/59.3 KB 220.0 kB/s eta 0:00:00
...
Successfully installed PrettyTable-3.11.0 PyYAML-6.0.2 annotated-types-0.7.0 attrs-24.2.0 autopage-0.5.2 caso-4.2.0 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.3.2 cliff-4.7.0 cmd2-2.4.3 cryptography-43.0.1 debtcollector-3.0.0 decorator-5.1.1 dirq-1.8 dogpile.cache-1.3.3 fasteners-0.19 idna-3.10 iso8601-2.1.0 jmespath-1.0.1 jsonpatch-1.33 jsonpointer-3.0.0 jsonschema-4.23.0 jsonschema-specifications-2023.12.1 keystoneauth1-5.8.0 msgpack-1.1.0 netaddr-1.3.0 netifaces-0.11.0 openstacksdk-4.0.0 os-client-config-2.1.0 os-service-types-1.7.0 osc-lib-3.1.0 oslo-utils-7.3.0 oslo.concurrency-6.1.0 oslo.config-9.6.0 oslo.context-5.6.0 oslo.i18n-6.4.0 oslo.log-6.1.2 oslo.serialization-5.5.0 packaging-24.1 pbr-6.1.0 platformdirs-4.3.6 pyOpenSSL-24.2.1 pycparser-2.22 pydantic-2.9.2 pydantic-core-2.23.4 pyparsing-3.1.4 pyperclip-1.9.0 python-cinderclient-9.6.0 python-dateutil-2.9.0.post0 python-glanceclient-4.7.0 python-keystoneclient-5.5.0 python-neutronclient-11.3.1 python-novaclient-18.7.0 referencing-0.35.1 requests-2.32.3 requestsexceptions-1.4.0 rfc3986-2.0.0 rpds-py-0.20.0 six-1.16.0 stevedore-5.3.0 typing-extensions-4.12.2 tzdata-2024.2 urllib3-2.2.3 warlock-2.0.1 wcwidth-0.2.13 wrapt-1.16.0

root@5ff66be7f372:/# python3 -mpip list | grep caso
caso                      4.2.0

root@5ff66be7f372:/# caso-extract --help
/usr/local/lib/python3.10/dist-packages/caso/record.py:105: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  @pydantic.validator("wall_duration", always=True)

/usr/local/lib/python3.10/dist-packages/caso/record.py:116: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  @pydantic.validator("cpu_duration", always=True)

/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)

Traceback (most recent call last):
  File "/usr/local/bin/caso-extract", line 5, in <module>
    from caso._cmd.extract import main
  File "/usr/local/lib/python3.10/dist-packages/caso/_cmd/extract.py", line 23, in <module>
    import caso.manager
  File "/usr/local/lib/python3.10/dist-packages/caso/manager.py", line 26, in <module>
    import caso.extract.manager
  File "/usr/local/lib/python3.10/dist-packages/caso/extract/__init__.py", line 19, in <module>
    from caso.extract.openstack import CinderExtractor
  File "/usr/local/lib/python3.10/dist-packages/caso/extract/openstack/__init__.py", line 19, in <module>
    from caso.extract.openstack.cinder import CinderExtractor
  File "/usr/local/lib/python3.10/dist-packages/caso/extract/openstack/cinder.py", line 26, in <module>
    from caso import record
  File "/usr/local/lib/python3.10/dist-packages/caso/record.py", line 62, in <module>
    class CloudRecord(_BaseRecord):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 115, in __new__
    private_attributes = inspect_namespace(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 428, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `public_ip_count = 0`. All model fields require a type annotation; if `public_ip_count` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.9/u/model-field-missing-annotation


root@5ff66be7f372:/# caso-extract --version
/usr/local/lib/python3.10/dist-packages/caso/record.py:105: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  @pydantic.validator("wall_duration", always=True)

/usr/local/lib/python3.10/dist-packages/caso/record.py:116: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  @pydantic.validator("cpu_duration", always=True)

/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)

Traceback (most recent call last):
  File "/usr/local/bin/caso-extract", line 5, in <module>
    from caso._cmd.extract import main
  File "/usr/local/lib/python3.10/dist-packages/caso/_cmd/extract.py", line 23, in <module>
    import caso.manager
  File "/usr/local/lib/python3.10/dist-packages/caso/manager.py", line 26, in <module>
    import caso.extract.manager
  File "/usr/local/lib/python3.10/dist-packages/caso/extract/__init__.py", line 19, in <module>
    from caso.extract.openstack import CinderExtractor
  File "/usr/local/lib/python3.10/dist-packages/caso/extract/openstack/__init__.py", line 19, in <module>
    from caso.extract.openstack.cinder import CinderExtractor
  File "/usr/local/lib/python3.10/dist-packages/caso/extract/openstack/cinder.py", line 26, in <module>
    from caso import record
  File "/usr/local/lib/python3.10/dist-packages/caso/record.py", line 62, in <module>
    class CloudRecord(_BaseRecord):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 115, in __new__
    private_attributes = inspect_namespace(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 428, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `public_ip_count = 0`. All model fields require a type annotation; if `public_ip_count` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.9/u/model-field-missing-annotation
```

**Comment by alvarolopez** [comment]
This is solved by https://github.com/IFCA-Advanced-Computing/caso/pull/119
